import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import {visualIdentityDiagnostics} from '../scripts/visual_identity.mjs';
import {compileScenePlan} from '../scripts/compile_scene_plan.mjs';
import {promptRealizationDiagnostics} from '../scripts/prompt_realization.mjs';

let count=0;
const test=(name,fn)=>{fn();count++;};
const rule='圈圈是大型灰蓝猫科阿尔法异兽，肩背宽厚，全身覆盖灰蓝斑驳短毛，无颈环；长尾连接蓬松尾端处有一个浅色小环。';
const state={scene:{location:'维修区'},characters:{},creatures:{圈圈:{present:true,visible:true,state:'无颈环',position:'低台旁'}}};
const context={rules:[rule],states:[state]};
const missing=(ctx,field)=>assert.ok(visualIdentityDiagnostics(ctx).some(e=>e.startsWith('VISUAL_IDENTITY_REQUIRED')&&e.includes(field)));
const global='2470年工业维修区，21:9横屏，写实摄影。高端动作概念片，电影级广告级画质，广告级商业调色，画面通透明亮、层次分明，色彩饱和自然不发灰，高光与材质光泽锐利。Schneider Hollywood Black Magic 1/8。镜头偏好手持镜头特写和近景。无任何中景 远景。非切镜情况下环境不跳变。对白或动作推进时，允许Seedance根据当前行动者、说话者、听者反应、人物关系和动作因果，自主决定全部运镜、景别变化、切镜数量与切换时点；不规定固定机位、镜头路径、人物画面占比或逐句镜头，只禁止退回展示完整空间和多人站位的空间全景。无字幕。无音乐。';
const plan=()=>({schema_version:'2.1',scene_id:'IDENTITY',profile:'production',scene_global_master:global,source:{path:'/tmp/final-script.md',status:'已确认'},initial_state:structuredClone(state),blocks:[{id:'IDENTITY-1',special_rules:['全程无台词','不生成旁白或画外人声。',rule],events:[{id:'E1',visible_action:'圈圈伏在低台旁。',effects:[]}]}]});
const prompt=rules=>['生成编号：IDENTITY-1','global：'+global,...['全程无台词','不生成旁白或画外人声。',...rules].map(r=>'特殊规则：'+r),'开始空间运动状态：圈圈伏在低台旁。','圈圈伏低身体。','结束空间运动状态：圈圈伏在低台旁。'].join('\n\n');

test('minimal current identity passes without inventing numerical measurements',()=>assert.deepEqual(visualIdentityDiagnostics(context),[]));
test('collar-only source regression fails',()=>missing({...context,rules:['圈圈无颈环。']},'大型猛兽体量'));
test('correct species alone does not supply scale',()=>missing({...context,rules:[rule.replace('大型','')]},'大型猛兽体量'));
test('a negative kitten warning is not a positive size description',()=>missing({...context,rules:[rule.replace('大型','')+'圈圈不生成小猫。']},'大型猛兽体量'));
test('a negated large animal does not supply size',()=>missing({...context,rules:[rule.replace('是大型','不是大型')]},'大型猛兽体量'));
test('missing coat fails independently of species and scale',()=>missing({...context,rules:[rule.replace('全身覆盖灰蓝斑驳短毛，','')]},'灰蓝斑驳短毛'));
test('enemy description cannot satisfy Quanquan',()=>missing({...context,rules:['圈圈无颈环。',rule.replaceAll('圈圈','敌方阿尔法01')]},'物种身份'));
test('a quoted name alone is not a visual appearance',()=>assert.deepEqual(visualIdentityDiagnostics({actionText:'乔昔（对步小蛮）说：“圈圈是大型猫科异兽。”'}),[]));
test('knowledge alone does not require a visible body',()=>assert.deepEqual(visualIdentityDiagnostics({actionText:'乔昔知道圈圈的藏身地点。'}),[]));
test('enemy command distinction does not introduce Quanquan',()=>assert.deepEqual(visualIdentityDiagnostics({rules:['敌方阿尔法01有控制颈环，与圈圈分属不同个体。','指令不传给圈圈。'],actionText:'敌方阿尔法01封住桥路。'}),[]));
test('an explicitly invisible creature does not acquire a description or upload',()=>{const s=structuredClone(state);s.creatures.圈圈.visible=false;assert.deepEqual(visualIdentityDiagnostics({states:[s]}),[]);});
test('a bound canonical image cannot replace text',()=>missing({assets:[{id:'WXGC-CHR-24700930-EP28-001'}]},'物种身份'));
test('visible action detects missing description without metadata',()=>missing({actionText:'圈圈先行，乔昔随后。'},'大型猛兽体量'));
test('current no-shell statement passes',()=>assert.deepEqual(visualIdentityDiagnostics({...context,rules:[rule+'圈圈无硬质皮层或甲片。']}),[]));
test('retired shell cannot return as positive anatomy',()=>assert.ok(visualIdentityDiagnostics({...context,rules:[rule+'圈圈颈部覆盖硬质皮层。']}).some(e=>e.startsWith('VISUAL_IDENTITY_CONFLICT'))));
test('compiler rejects omission before prompt projection',()=>{const p=plan();p.blocks[0].special_rules=['圈圈无颈环。'];assert.throws(()=>compileScenePlan(p),/VISUAL_IDENTITY_REQUIRED/);});
test('compiler preserves supplied description and does not modify source plan',()=>{const p=plan(),before=JSON.stringify(p),c=compileScenePlan(p);assert.equal(JSON.stringify(p),before);assert.ok(c.blocks[0].special_rules.includes(rule));});
test('next independent block cannot inherit the preceding prose rule',()=>{const p=plan();p.blocks.push({id:'IDENTITY-2',events:[{id:'E2',visible_action:'圈圈伏在低台旁。',effects:[]}]});assert.throws(()=>compileScenePlan(p),/IDENTITY-2.*VISUAL_IDENTITY_REQUIRED/);});
test('appearance during an intermediate state also requires text',()=>{const p=plan();p.initial_state.creatures.圈圈.visible=false;p.blocks[0].special_rules=[];p.blocks[0].events=[{id:'E1',visible_action:'通路亮起。',effects:[{path:'creatures.圈圈.visible',set:true}]},{id:'E2',visible_action:'通路遮挡恢复。',effects:[{path:'creatures.圈圈.visible',set:false}]}];assert.throws(()=>compileScenePlan(p),/VISUAL_IDENTITY_REQUIRED/);});
test('final prompt cannot lose the rule after successful compilation',()=>{compileScenePlan(plan());assert.ok(promptRealizationDiagnostics(prompt(['圈圈无颈环。']),{startState:state,endState:state}).some(e=>e.startsWith('VISUAL_IDENTITY_REQUIRED')));assert.deepEqual(promptRealizationDiagnostics(prompt([rule]),{startState:state,endState:state}),[]);});
test('global is not an allowed substitute for local identity',()=>{const p=prompt([]).replace('global：','global：'+rule);assert.ok(promptRealizationDiagnostics(p,{startState:state}).some(e=>e.startsWith('VISUAL_IDENTITY_REQUIRED')));});
test('delivery loader rejects a missing description before rendering',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'identity-test-'));try{const file=path.join(dir,'manifest.json');fs.writeFileSync(file,JSON.stringify({title:'test',blocks:[{id:'IDENTITY-1',duration_status:'未实测',prompt:prompt(['圈圈无颈环。']),assets:[{id:'WXGC-CHR-24700930-EP28-001',path:'/tmp/example/circle.jpg'}]}]}));const loader=new URL('../scripts/render_prompt_delivery_html.mjs',import.meta.url).href;const r=spawnSync(process.execPath,['--input-type=module','-e',`import {loadManifest} from ${JSON.stringify(loader)};loadManifest(${JSON.stringify(file)});`],{encoding:'utf8'});assert.notEqual(r.status,0);assert.match(r.stderr,/VISUAL_IDENTITY_REQUIRED/);}finally{fs.rmSync(dir,{recursive:true,force:true});}});
console.log(`OK: ${count} visual identity regression tests passed`);
